/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteRouteImport } from './routes/$slug.route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugCategoryRouteImport } from './routes/$slug.$category'
import { Route as SlugAccountRouteImport } from './routes/$slug.account'
import { Route as SlugAuthRouteImport } from './routes/$slug.auth'
import { Route as SlugAuthConfirmedRouteImport } from './routes/$slug.auth-confirmed'
import { Route as SlugCheckoutRouteImport } from './routes/$slug.checkout'
import { Route as SlugSearchRouteImport } from './routes/$slug.search'
import { Route as SlugWishlistRouteImport } from './routes/$slug.wishlist'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as PlatformFilenameRouteImport } from './routes/platform.$filename'
import { Route as SlugPageIdxRouteImport } from './routes/$slug.page.$idx'
import { Route as SlugProductSplatRouteImport } from './routes/$slug.product.$'
import { Route as SlugProductIdRouteImport } from './routes/$slug.product.$id'
import { Route as SlugThankYouOrderIdRouteImport } from './routes/$slug.thank-you.$orderId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBrandsRouteImport } from './routes/_authenticated/admin.brands'
import { Route as AuthenticatedAdminCampaignsRouteImport } from './routes/_authenticated/admin.campaigns'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminExpensesRouteImport } from './routes/_authenticated/admin.expenses'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin.inventory'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as ApiCronCleanupBenefitReceiptsRouteImport } from './routes/api.cron.cleanup-benefit-receipts'
import { Route as ApiOrdersStatusRouteImport } from './routes/api.orders.status'
import { Route as AuthenticatedAdminBSlugRouteRouteImport } from './routes/_authenticated/admin.b.$slug.route'
import { Route as AuthenticatedAdminSuperRequestsRouteImport } from './routes/_authenticated/admin.super.requests'
import { Route as AuthenticatedAdminSuperSettingsRouteImport } from './routes/_authenticated/admin.super.settings'
import { Route as ApiPublicPaymentsCreateTapChargeRouteImport } from './routes/api.public.payments.create-tap-charge'
import { Route as ApiPublicPaymentsTapRedirectRouteImport } from './routes/api.public.payments.tap-redirect'
import { Route as ApiPublicWebhooksTapRouteImport } from './routes/api.public.webhooks.tap'
import { Route as BrandsBrandIdKindFilenameRouteImport } from './routes/brands.$brandId.$kind.$filename'
import { Route as AuthenticatedAdminBSlugCampaignsRouteImport } from './routes/_authenticated/admin.b.$slug.campaigns'
import { Route as AuthenticatedAdminBSlugCategoriesRouteImport } from './routes/_authenticated/admin.b.$slug.categories'
import { Route as AuthenticatedAdminBSlugCommunicationsRouteImport } from './routes/_authenticated/admin.b.$slug.communications'
import { Route as AuthenticatedAdminBSlugCustomersRouteImport } from './routes/_authenticated/admin.b.$slug.customers'
import { Route as AuthenticatedAdminBSlugDashboardRouteImport } from './routes/_authenticated/admin.b.$slug.dashboard'
import { Route as AuthenticatedAdminBSlugDiscountsRouteImport } from './routes/_authenticated/admin.b.$slug.discounts'
import { Route as AuthenticatedAdminBSlugExpensesRouteImport } from './routes/_authenticated/admin.b.$slug.expenses'
import { Route as AuthenticatedAdminBSlugIntegrationsRouteImport } from './routes/_authenticated/admin.b.$slug.integrations'
import { Route as AuthenticatedAdminBSlugInventoryRouteImport } from './routes/_authenticated/admin.b.$slug.inventory'
import { Route as AuthenticatedAdminBSlugPagesRouteImport } from './routes/_authenticated/admin.b.$slug.pages'
import { Route as AuthenticatedAdminBSlugReportsRouteImport } from './routes/_authenticated/admin.b.$slug.reports'
import { Route as AuthenticatedAdminBSlugSettingsRouteImport } from './routes/_authenticated/admin.b.$slug.settings'
import { Route as AuthenticatedAdminBSlugTeamRouteImport } from './routes/_authenticated/admin.b.$slug.team'
import { Route as AuthenticatedAdminBSlugCustomersCustomerIdRouteImport } from './routes/_authenticated/admin.b.$slug.customers.$customerId'
import { Route as AuthenticatedAdminBSlugOrdersIndexRouteImport } from './routes/_authenticated/admin.b.$slug.orders.index'
import { Route as AuthenticatedAdminBSlugOrdersIdRouteImport } from './routes/_authenticated/admin.b.$slug.orders.$id'
import { Route as AuthenticatedAdminBSlugReportsIndexRouteImport } from './routes/_authenticated/admin.b.$slug.reports.index'
import { Route as AuthenticatedAdminBSlugReportsCustomersRouteImport } from './routes/_authenticated/admin.b.$slug.reports.customers'
import { Route as AuthenticatedAdminBSlugReportsExportRouteImport } from './routes/_authenticated/admin.b.$slug.reports.export'
import { Route as AuthenticatedAdminBSlugReportsProductsRouteImport } from './routes/_authenticated/admin.b.$slug.reports.products'
import { Route as AuthenticatedAdminBSlugReportsSalesRouteImport } from './routes/_authenticated/admin.b.$slug.reports.sales'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRouteRoute = SlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugCategoryRoute = SlugCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugAccountRoute = SlugAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugAuthRoute = SlugAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugAuthConfirmedRoute = SlugAuthConfirmedRouteImport.update({
  id: '/auth-confirmed',
  path: '/auth-confirmed',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugCheckoutRoute = SlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugSearchRoute = SlugSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugWishlistRoute = SlugWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => SlugRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformFilenameRoute = PlatformFilenameRouteImport.update({
  id: '/platform/$filename',
  path: '/platform/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugPageIdxRoute = SlugPageIdxRouteImport.update({
  id: '/page/$idx',
  path: '/page/$idx',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugProductSplatRoute = SlugProductSplatRouteImport.update({
  id: '/product/$',
  path: '/product/$',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugProductIdRoute = SlugProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugThankYouOrderIdRoute = SlugThankYouOrderIdRouteImport.update({
  id: '/thank-you/$orderId',
  path: '/thank-you/$orderId',
  getParentRoute: () => SlugRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBrandsRoute =
  AuthenticatedAdminBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCampaignsRoute =
  AuthenticatedAdminCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExpensesRoute =
  AuthenticatedAdminExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiCronCleanupBenefitReceiptsRoute =
  ApiCronCleanupBenefitReceiptsRouteImport.update({
    id: '/api/cron/cleanup-benefit-receipts',
    path: '/api/cron/cleanup-benefit-receipts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrdersStatusRoute = ApiOrdersStatusRouteImport.update({
  id: '/api/orders/status',
  path: '/api/orders/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminBSlugRouteRoute =
  AuthenticatedAdminBSlugRouteRouteImport.update({
    id: '/b/$slug',
    path: '/b/$slug',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuperRequestsRoute =
  AuthenticatedAdminSuperRequestsRouteImport.update({
    id: '/super/requests',
    path: '/super/requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuperSettingsRoute =
  AuthenticatedAdminSuperSettingsRouteImport.update({
    id: '/super/settings',
    path: '/super/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicPaymentsCreateTapChargeRoute =
  ApiPublicPaymentsCreateTapChargeRouteImport.update({
    id: '/api/public/payments/create-tap-charge',
    path: '/api/public/payments/create-tap-charge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsTapRedirectRoute =
  ApiPublicPaymentsTapRedirectRouteImport.update({
    id: '/api/public/payments/tap-redirect',
    path: '/api/public/payments/tap-redirect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksTapRoute = ApiPublicWebhooksTapRouteImport.update({
  id: '/api/public/webhooks/tap',
  path: '/api/public/webhooks/tap',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdKindFilenameRoute =
  BrandsBrandIdKindFilenameRouteImport.update({
    id: '/brands/$brandId/$kind/$filename',
    path: '/brands/$brandId/$kind/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminBSlugCampaignsRoute =
  AuthenticatedAdminBSlugCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugCategoriesRoute =
  AuthenticatedAdminBSlugCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugCommunicationsRoute =
  AuthenticatedAdminBSlugCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugCustomersRoute =
  AuthenticatedAdminBSlugCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugDashboardRoute =
  AuthenticatedAdminBSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugDiscountsRoute =
  AuthenticatedAdminBSlugDiscountsRouteImport.update({
    id: '/discounts',
    path: '/discounts',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugExpensesRoute =
  AuthenticatedAdminBSlugExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugIntegrationsRoute =
  AuthenticatedAdminBSlugIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugInventoryRoute =
  AuthenticatedAdminBSlugInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugPagesRoute =
  AuthenticatedAdminBSlugPagesRouteImport.update({
    id: '/pages',
    path: '/pages',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugReportsRoute =
  AuthenticatedAdminBSlugReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugSettingsRoute =
  AuthenticatedAdminBSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugTeamRoute =
  AuthenticatedAdminBSlugTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugCustomersCustomerIdRoute =
  AuthenticatedAdminBSlugCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedAdminBSlugCustomersRoute,
  } as any)
const AuthenticatedAdminBSlugOrdersIndexRoute =
  AuthenticatedAdminBSlugOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugOrdersIdRoute =
  AuthenticatedAdminBSlugOrdersIdRouteImport.update({
    id: '/orders/$id',
    path: '/orders/$id',
    getParentRoute: () => AuthenticatedAdminBSlugRouteRoute,
  } as any)
const AuthenticatedAdminBSlugReportsIndexRoute =
  AuthenticatedAdminBSlugReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminBSlugReportsRoute,
  } as any)
const AuthenticatedAdminBSlugReportsCustomersRoute =
  AuthenticatedAdminBSlugReportsCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminBSlugReportsRoute,
  } as any)
const AuthenticatedAdminBSlugReportsExportRoute =
  AuthenticatedAdminBSlugReportsExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedAdminBSlugReportsRoute,
  } as any)
const AuthenticatedAdminBSlugReportsProductsRoute =
  AuthenticatedAdminBSlugReportsProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminBSlugReportsRoute,
  } as any)
const AuthenticatedAdminBSlugReportsSalesRoute =
  AuthenticatedAdminBSlugReportsSalesRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => AuthenticatedAdminBSlugReportsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboard': typeof OnboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$slug/$category': typeof SlugCategoryRoute
  '/$slug/account': typeof SlugAccountRoute
  '/$slug/auth': typeof SlugAuthRoute
  '/$slug/auth-confirmed': typeof SlugAuthConfirmedRoute
  '/$slug/checkout': typeof SlugCheckoutRoute
  '/$slug/search': typeof SlugSearchRoute
  '/$slug/wishlist': typeof SlugWishlistRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/invoice/$id': typeof InvoiceIdRoute
  '/platform/$filename': typeof PlatformFilenameRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/page/$idx': typeof SlugPageIdxRoute
  '/$slug/product/$': typeof SlugProductSplatRoute
  '/$slug/product/$id': typeof SlugProductIdRoute
  '/$slug/thank-you/$orderId': typeof SlugThankYouOrderIdRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/cron/cleanup-benefit-receipts': typeof ApiCronCleanupBenefitReceiptsRoute
  '/api/orders/status': typeof ApiOrdersStatusRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/b/$slug': typeof AuthenticatedAdminBSlugRouteRouteWithChildren
  '/admin/super/requests': typeof AuthenticatedAdminSuperRequestsRoute
  '/admin/super/settings': typeof AuthenticatedAdminSuperSettingsRoute
  '/api/public/payments/create-tap-charge': typeof ApiPublicPaymentsCreateTapChargeRoute
  '/api/public/payments/tap-redirect': typeof ApiPublicPaymentsTapRedirectRoute
  '/api/public/webhooks/tap': typeof ApiPublicWebhooksTapRoute
  '/brands/$brandId/$kind/$filename': typeof BrandsBrandIdKindFilenameRoute
  '/admin/b/$slug/campaigns': typeof AuthenticatedAdminBSlugCampaignsRoute
  '/admin/b/$slug/categories': typeof AuthenticatedAdminBSlugCategoriesRoute
  '/admin/b/$slug/communications': typeof AuthenticatedAdminBSlugCommunicationsRoute
  '/admin/b/$slug/customers': typeof AuthenticatedAdminBSlugCustomersRouteWithChildren
  '/admin/b/$slug/dashboard': typeof AuthenticatedAdminBSlugDashboardRoute
  '/admin/b/$slug/discounts': typeof AuthenticatedAdminBSlugDiscountsRoute
  '/admin/b/$slug/expenses': typeof AuthenticatedAdminBSlugExpensesRoute
  '/admin/b/$slug/integrations': typeof AuthenticatedAdminBSlugIntegrationsRoute
  '/admin/b/$slug/inventory': typeof AuthenticatedAdminBSlugInventoryRoute
  '/admin/b/$slug/pages': typeof AuthenticatedAdminBSlugPagesRoute
  '/admin/b/$slug/reports': typeof AuthenticatedAdminBSlugReportsRouteWithChildren
  '/admin/b/$slug/settings': typeof AuthenticatedAdminBSlugSettingsRoute
  '/admin/b/$slug/team': typeof AuthenticatedAdminBSlugTeamRoute
  '/admin/b/$slug/customers/$customerId': typeof AuthenticatedAdminBSlugCustomersCustomerIdRoute
  '/admin/b/$slug/orders/$id': typeof AuthenticatedAdminBSlugOrdersIdRoute
  '/admin/b/$slug/reports/customers': typeof AuthenticatedAdminBSlugReportsCustomersRoute
  '/admin/b/$slug/reports/export': typeof AuthenticatedAdminBSlugReportsExportRoute
  '/admin/b/$slug/reports/products': typeof AuthenticatedAdminBSlugReportsProductsRoute
  '/admin/b/$slug/reports/sales': typeof AuthenticatedAdminBSlugReportsSalesRoute
  '/admin/b/$slug/orders/': typeof AuthenticatedAdminBSlugOrdersIndexRoute
  '/admin/b/$slug/reports/': typeof AuthenticatedAdminBSlugReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboard': typeof OnboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$slug/$category': typeof SlugCategoryRoute
  '/$slug/account': typeof SlugAccountRoute
  '/$slug/auth': typeof SlugAuthRoute
  '/$slug/auth-confirmed': typeof SlugAuthConfirmedRoute
  '/$slug/checkout': typeof SlugCheckoutRoute
  '/$slug/search': typeof SlugSearchRoute
  '/$slug/wishlist': typeof SlugWishlistRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/platform/$filename': typeof PlatformFilenameRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/page/$idx': typeof SlugPageIdxRoute
  '/$slug/product/$': typeof SlugProductSplatRoute
  '/$slug/product/$id': typeof SlugProductIdRoute
  '/$slug/thank-you/$orderId': typeof SlugThankYouOrderIdRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/cron/cleanup-benefit-receipts': typeof ApiCronCleanupBenefitReceiptsRoute
  '/api/orders/status': typeof ApiOrdersStatusRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/b/$slug': typeof AuthenticatedAdminBSlugRouteRouteWithChildren
  '/admin/super/requests': typeof AuthenticatedAdminSuperRequestsRoute
  '/admin/super/settings': typeof AuthenticatedAdminSuperSettingsRoute
  '/api/public/payments/create-tap-charge': typeof ApiPublicPaymentsCreateTapChargeRoute
  '/api/public/payments/tap-redirect': typeof ApiPublicPaymentsTapRedirectRoute
  '/api/public/webhooks/tap': typeof ApiPublicWebhooksTapRoute
  '/brands/$brandId/$kind/$filename': typeof BrandsBrandIdKindFilenameRoute
  '/admin/b/$slug/campaigns': typeof AuthenticatedAdminBSlugCampaignsRoute
  '/admin/b/$slug/categories': typeof AuthenticatedAdminBSlugCategoriesRoute
  '/admin/b/$slug/communications': typeof AuthenticatedAdminBSlugCommunicationsRoute
  '/admin/b/$slug/customers': typeof AuthenticatedAdminBSlugCustomersRouteWithChildren
  '/admin/b/$slug/dashboard': typeof AuthenticatedAdminBSlugDashboardRoute
  '/admin/b/$slug/discounts': typeof AuthenticatedAdminBSlugDiscountsRoute
  '/admin/b/$slug/expenses': typeof AuthenticatedAdminBSlugExpensesRoute
  '/admin/b/$slug/integrations': typeof AuthenticatedAdminBSlugIntegrationsRoute
  '/admin/b/$slug/inventory': typeof AuthenticatedAdminBSlugInventoryRoute
  '/admin/b/$slug/pages': typeof AuthenticatedAdminBSlugPagesRoute
  '/admin/b/$slug/settings': typeof AuthenticatedAdminBSlugSettingsRoute
  '/admin/b/$slug/team': typeof AuthenticatedAdminBSlugTeamRoute
  '/admin/b/$slug/customers/$customerId': typeof AuthenticatedAdminBSlugCustomersCustomerIdRoute
  '/admin/b/$slug/orders/$id': typeof AuthenticatedAdminBSlugOrdersIdRoute
  '/admin/b/$slug/reports/customers': typeof AuthenticatedAdminBSlugReportsCustomersRoute
  '/admin/b/$slug/reports/export': typeof AuthenticatedAdminBSlugReportsExportRoute
  '/admin/b/$slug/reports/products': typeof AuthenticatedAdminBSlugReportsProductsRoute
  '/admin/b/$slug/reports/sales': typeof AuthenticatedAdminBSlugReportsSalesRoute
  '/admin/b/$slug/orders': typeof AuthenticatedAdminBSlugOrdersIndexRoute
  '/admin/b/$slug/reports': typeof AuthenticatedAdminBSlugReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboard': typeof OnboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$slug/$category': typeof SlugCategoryRoute
  '/$slug/account': typeof SlugAccountRoute
  '/$slug/auth': typeof SlugAuthRoute
  '/$slug/auth-confirmed': typeof SlugAuthConfirmedRoute
  '/$slug/checkout': typeof SlugCheckoutRoute
  '/$slug/search': typeof SlugSearchRoute
  '/$slug/wishlist': typeof SlugWishlistRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/invoice/$id': typeof InvoiceIdRoute
  '/platform/$filename': typeof PlatformFilenameRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/page/$idx': typeof SlugPageIdxRoute
  '/$slug/product/$': typeof SlugProductSplatRoute
  '/$slug/product/$id': typeof SlugProductIdRoute
  '/$slug/thank-you/$orderId': typeof SlugThankYouOrderIdRoute
  '/_authenticated/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/_authenticated/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/cron/cleanup-benefit-receipts': typeof ApiCronCleanupBenefitReceiptsRoute
  '/api/orders/status': typeof ApiOrdersStatusRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/b/$slug': typeof AuthenticatedAdminBSlugRouteRouteWithChildren
  '/_authenticated/admin/super/requests': typeof AuthenticatedAdminSuperRequestsRoute
  '/_authenticated/admin/super/settings': typeof AuthenticatedAdminSuperSettingsRoute
  '/api/public/payments/create-tap-charge': typeof ApiPublicPaymentsCreateTapChargeRoute
  '/api/public/payments/tap-redirect': typeof ApiPublicPaymentsTapRedirectRoute
  '/api/public/webhooks/tap': typeof ApiPublicWebhooksTapRoute
  '/brands/$brandId/$kind/$filename': typeof BrandsBrandIdKindFilenameRoute
  '/_authenticated/admin/b/$slug/campaigns': typeof AuthenticatedAdminBSlugCampaignsRoute
  '/_authenticated/admin/b/$slug/categories': typeof AuthenticatedAdminBSlugCategoriesRoute
  '/_authenticated/admin/b/$slug/communications': typeof AuthenticatedAdminBSlugCommunicationsRoute
  '/_authenticated/admin/b/$slug/customers': typeof AuthenticatedAdminBSlugCustomersRouteWithChildren
  '/_authenticated/admin/b/$slug/dashboard': typeof AuthenticatedAdminBSlugDashboardRoute
  '/_authenticated/admin/b/$slug/discounts': typeof AuthenticatedAdminBSlugDiscountsRoute
  '/_authenticated/admin/b/$slug/expenses': typeof AuthenticatedAdminBSlugExpensesRoute
  '/_authenticated/admin/b/$slug/integrations': typeof AuthenticatedAdminBSlugIntegrationsRoute
  '/_authenticated/admin/b/$slug/inventory': typeof AuthenticatedAdminBSlugInventoryRoute
  '/_authenticated/admin/b/$slug/pages': typeof AuthenticatedAdminBSlugPagesRoute
  '/_authenticated/admin/b/$slug/reports': typeof AuthenticatedAdminBSlugReportsRouteWithChildren
  '/_authenticated/admin/b/$slug/settings': typeof AuthenticatedAdminBSlugSettingsRoute
  '/_authenticated/admin/b/$slug/team': typeof AuthenticatedAdminBSlugTeamRoute
  '/_authenticated/admin/b/$slug/customers/$customerId': typeof AuthenticatedAdminBSlugCustomersCustomerIdRoute
  '/_authenticated/admin/b/$slug/orders/$id': typeof AuthenticatedAdminBSlugOrdersIdRoute
  '/_authenticated/admin/b/$slug/reports/customers': typeof AuthenticatedAdminBSlugReportsCustomersRoute
  '/_authenticated/admin/b/$slug/reports/export': typeof AuthenticatedAdminBSlugReportsExportRoute
  '/_authenticated/admin/b/$slug/reports/products': typeof AuthenticatedAdminBSlugReportsProductsRoute
  '/_authenticated/admin/b/$slug/reports/sales': typeof AuthenticatedAdminBSlugReportsSalesRoute
  '/_authenticated/admin/b/$slug/orders/': typeof AuthenticatedAdminBSlugOrdersIndexRoute
  '/_authenticated/admin/b/$slug/reports/': typeof AuthenticatedAdminBSlugReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/forgot-password'
    | '/onboard'
    | '/reset-password'
    | '/$slug/$category'
    | '/$slug/account'
    | '/$slug/auth'
    | '/$slug/auth-confirmed'
    | '/$slug/checkout'
    | '/$slug/search'
    | '/$slug/wishlist'
    | '/admin'
    | '/invoice/$id'
    | '/platform/$filename'
    | '/$slug/'
    | '/$slug/page/$idx'
    | '/$slug/product/$'
    | '/$slug/product/$id'
    | '/$slug/thank-you/$orderId'
    | '/admin/brands'
    | '/admin/campaigns'
    | '/admin/customers'
    | '/admin/expenses'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/team'
    | '/api/cron/cleanup-benefit-receipts'
    | '/api/orders/status'
    | '/admin/'
    | '/admin/b/$slug'
    | '/admin/super/requests'
    | '/admin/super/settings'
    | '/api/public/payments/create-tap-charge'
    | '/api/public/payments/tap-redirect'
    | '/api/public/webhooks/tap'
    | '/brands/$brandId/$kind/$filename'
    | '/admin/b/$slug/campaigns'
    | '/admin/b/$slug/categories'
    | '/admin/b/$slug/communications'
    | '/admin/b/$slug/customers'
    | '/admin/b/$slug/dashboard'
    | '/admin/b/$slug/discounts'
    | '/admin/b/$slug/expenses'
    | '/admin/b/$slug/integrations'
    | '/admin/b/$slug/inventory'
    | '/admin/b/$slug/pages'
    | '/admin/b/$slug/reports'
    | '/admin/b/$slug/settings'
    | '/admin/b/$slug/team'
    | '/admin/b/$slug/customers/$customerId'
    | '/admin/b/$slug/orders/$id'
    | '/admin/b/$slug/reports/customers'
    | '/admin/b/$slug/reports/export'
    | '/admin/b/$slug/reports/products'
    | '/admin/b/$slug/reports/sales'
    | '/admin/b/$slug/orders/'
    | '/admin/b/$slug/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/onboard'
    | '/reset-password'
    | '/$slug/$category'
    | '/$slug/account'
    | '/$slug/auth'
    | '/$slug/auth-confirmed'
    | '/$slug/checkout'
    | '/$slug/search'
    | '/$slug/wishlist'
    | '/invoice/$id'
    | '/platform/$filename'
    | '/$slug'
    | '/$slug/page/$idx'
    | '/$slug/product/$'
    | '/$slug/product/$id'
    | '/$slug/thank-you/$orderId'
    | '/admin/brands'
    | '/admin/campaigns'
    | '/admin/customers'
    | '/admin/expenses'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/team'
    | '/api/cron/cleanup-benefit-receipts'
    | '/api/orders/status'
    | '/admin'
    | '/admin/b/$slug'
    | '/admin/super/requests'
    | '/admin/super/settings'
    | '/api/public/payments/create-tap-charge'
    | '/api/public/payments/tap-redirect'
    | '/api/public/webhooks/tap'
    | '/brands/$brandId/$kind/$filename'
    | '/admin/b/$slug/campaigns'
    | '/admin/b/$slug/categories'
    | '/admin/b/$slug/communications'
    | '/admin/b/$slug/customers'
    | '/admin/b/$slug/dashboard'
    | '/admin/b/$slug/discounts'
    | '/admin/b/$slug/expenses'
    | '/admin/b/$slug/integrations'
    | '/admin/b/$slug/inventory'
    | '/admin/b/$slug/pages'
    | '/admin/b/$slug/settings'
    | '/admin/b/$slug/team'
    | '/admin/b/$slug/customers/$customerId'
    | '/admin/b/$slug/orders/$id'
    | '/admin/b/$slug/reports/customers'
    | '/admin/b/$slug/reports/export'
    | '/admin/b/$slug/reports/products'
    | '/admin/b/$slug/reports/sales'
    | '/admin/b/$slug/orders'
    | '/admin/b/$slug/reports'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/onboard'
    | '/reset-password'
    | '/$slug/$category'
    | '/$slug/account'
    | '/$slug/auth'
    | '/$slug/auth-confirmed'
    | '/$slug/checkout'
    | '/$slug/search'
    | '/$slug/wishlist'
    | '/_authenticated/admin'
    | '/invoice/$id'
    | '/platform/$filename'
    | '/$slug/'
    | '/$slug/page/$idx'
    | '/$slug/product/$'
    | '/$slug/product/$id'
    | '/$slug/thank-you/$orderId'
    | '/_authenticated/admin/brands'
    | '/_authenticated/admin/campaigns'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/expenses'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/team'
    | '/api/cron/cleanup-benefit-receipts'
    | '/api/orders/status'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/b/$slug'
    | '/_authenticated/admin/super/requests'
    | '/_authenticated/admin/super/settings'
    | '/api/public/payments/create-tap-charge'
    | '/api/public/payments/tap-redirect'
    | '/api/public/webhooks/tap'
    | '/brands/$brandId/$kind/$filename'
    | '/_authenticated/admin/b/$slug/campaigns'
    | '/_authenticated/admin/b/$slug/categories'
    | '/_authenticated/admin/b/$slug/communications'
    | '/_authenticated/admin/b/$slug/customers'
    | '/_authenticated/admin/b/$slug/dashboard'
    | '/_authenticated/admin/b/$slug/discounts'
    | '/_authenticated/admin/b/$slug/expenses'
    | '/_authenticated/admin/b/$slug/integrations'
    | '/_authenticated/admin/b/$slug/inventory'
    | '/_authenticated/admin/b/$slug/pages'
    | '/_authenticated/admin/b/$slug/reports'
    | '/_authenticated/admin/b/$slug/settings'
    | '/_authenticated/admin/b/$slug/team'
    | '/_authenticated/admin/b/$slug/customers/$customerId'
    | '/_authenticated/admin/b/$slug/orders/$id'
    | '/_authenticated/admin/b/$slug/reports/customers'
    | '/_authenticated/admin/b/$slug/reports/export'
    | '/_authenticated/admin/b/$slug/reports/products'
    | '/_authenticated/admin/b/$slug/reports/sales'
    | '/_authenticated/admin/b/$slug/orders/'
    | '/_authenticated/admin/b/$slug/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRouteRoute: typeof SlugRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardRoute: typeof OnboardRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  PlatformFilenameRoute: typeof PlatformFilenameRoute
  ApiCronCleanupBenefitReceiptsRoute: typeof ApiCronCleanupBenefitReceiptsRoute
  ApiOrdersStatusRoute: typeof ApiOrdersStatusRoute
  ApiPublicPaymentsCreateTapChargeRoute: typeof ApiPublicPaymentsCreateTapChargeRoute
  ApiPublicPaymentsTapRedirectRoute: typeof ApiPublicPaymentsTapRedirectRoute
  ApiPublicWebhooksTapRoute: typeof ApiPublicWebhooksTapRoute
  BrandsBrandIdKindFilenameRoute: typeof BrandsBrandIdKindFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/$category': {
      id: '/$slug/$category'
      path: '/$category'
      fullPath: '/$slug/$category'
      preLoaderRoute: typeof SlugCategoryRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/account': {
      id: '/$slug/account'
      path: '/account'
      fullPath: '/$slug/account'
      preLoaderRoute: typeof SlugAccountRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/auth': {
      id: '/$slug/auth'
      path: '/auth'
      fullPath: '/$slug/auth'
      preLoaderRoute: typeof SlugAuthRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/auth-confirmed': {
      id: '/$slug/auth-confirmed'
      path: '/auth-confirmed'
      fullPath: '/$slug/auth-confirmed'
      preLoaderRoute: typeof SlugAuthConfirmedRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/checkout': {
      id: '/$slug/checkout'
      path: '/checkout'
      fullPath: '/$slug/checkout'
      preLoaderRoute: typeof SlugCheckoutRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/search': {
      id: '/$slug/search'
      path: '/search'
      fullPath: '/$slug/search'
      preLoaderRoute: typeof SlugSearchRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/wishlist': {
      id: '/$slug/wishlist'
      path: '/wishlist'
      fullPath: '/$slug/wishlist'
      preLoaderRoute: typeof SlugWishlistRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/$filename': {
      id: '/platform/$filename'
      path: '/platform/$filename'
      fullPath: '/platform/$filename'
      preLoaderRoute: typeof PlatformFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/page/$idx': {
      id: '/$slug/page/$idx'
      path: '/page/$idx'
      fullPath: '/$slug/page/$idx'
      preLoaderRoute: typeof SlugPageIdxRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/product/$': {
      id: '/$slug/product/$'
      path: '/product/$'
      fullPath: '/$slug/product/$'
      preLoaderRoute: typeof SlugProductSplatRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/product/$id': {
      id: '/$slug/product/$id'
      path: '/product/$id'
      fullPath: '/$slug/product/$id'
      preLoaderRoute: typeof SlugProductIdRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/thank-you/$orderId': {
      id: '/$slug/thank-you/$orderId'
      path: '/thank-you/$orderId'
      fullPath: '/$slug/thank-you/$orderId'
      preLoaderRoute: typeof SlugThankYouOrderIdRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/brands': {
      id: '/_authenticated/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AuthenticatedAdminBrandsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/campaigns': {
      id: '/_authenticated/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/expenses': {
      id: '/_authenticated/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AuthenticatedAdminExpensesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/cron/cleanup-benefit-receipts': {
      id: '/api/cron/cleanup-benefit-receipts'
      path: '/api/cron/cleanup-benefit-receipts'
      fullPath: '/api/cron/cleanup-benefit-receipts'
      preLoaderRoute: typeof ApiCronCleanupBenefitReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/status': {
      id: '/api/orders/status'
      path: '/api/orders/status'
      fullPath: '/api/orders/status'
      preLoaderRoute: typeof ApiOrdersStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/b/$slug': {
      id: '/_authenticated/admin/b/$slug'
      path: '/b/$slug'
      fullPath: '/admin/b/$slug'
      preLoaderRoute: typeof AuthenticatedAdminBSlugRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/super/requests': {
      id: '/_authenticated/admin/super/requests'
      path: '/super/requests'
      fullPath: '/admin/super/requests'
      preLoaderRoute: typeof AuthenticatedAdminSuperRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/super/settings': {
      id: '/_authenticated/admin/super/settings'
      path: '/super/settings'
      fullPath: '/admin/super/settings'
      preLoaderRoute: typeof AuthenticatedAdminSuperSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/payments/create-tap-charge': {
      id: '/api/public/payments/create-tap-charge'
      path: '/api/public/payments/create-tap-charge'
      fullPath: '/api/public/payments/create-tap-charge'
      preLoaderRoute: typeof ApiPublicPaymentsCreateTapChargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/tap-redirect': {
      id: '/api/public/payments/tap-redirect'
      path: '/api/public/payments/tap-redirect'
      fullPath: '/api/public/payments/tap-redirect'
      preLoaderRoute: typeof ApiPublicPaymentsTapRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/tap': {
      id: '/api/public/webhooks/tap'
      path: '/api/public/webhooks/tap'
      fullPath: '/api/public/webhooks/tap'
      preLoaderRoute: typeof ApiPublicWebhooksTapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/$kind/$filename': {
      id: '/brands/$brandId/$kind/$filename'
      path: '/brands/$brandId/$kind/$filename'
      fullPath: '/brands/$brandId/$kind/$filename'
      preLoaderRoute: typeof BrandsBrandIdKindFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/b/$slug/campaigns': {
      id: '/_authenticated/admin/b/$slug/campaigns'
      path: '/campaigns'
      fullPath: '/admin/b/$slug/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminBSlugCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/categories': {
      id: '/_authenticated/admin/b/$slug/categories'
      path: '/categories'
      fullPath: '/admin/b/$slug/categories'
      preLoaderRoute: typeof AuthenticatedAdminBSlugCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/communications': {
      id: '/_authenticated/admin/b/$slug/communications'
      path: '/communications'
      fullPath: '/admin/b/$slug/communications'
      preLoaderRoute: typeof AuthenticatedAdminBSlugCommunicationsRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/customers': {
      id: '/_authenticated/admin/b/$slug/customers'
      path: '/customers'
      fullPath: '/admin/b/$slug/customers'
      preLoaderRoute: typeof AuthenticatedAdminBSlugCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/dashboard': {
      id: '/_authenticated/admin/b/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/admin/b/$slug/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminBSlugDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/discounts': {
      id: '/_authenticated/admin/b/$slug/discounts'
      path: '/discounts'
      fullPath: '/admin/b/$slug/discounts'
      preLoaderRoute: typeof AuthenticatedAdminBSlugDiscountsRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/expenses': {
      id: '/_authenticated/admin/b/$slug/expenses'
      path: '/expenses'
      fullPath: '/admin/b/$slug/expenses'
      preLoaderRoute: typeof AuthenticatedAdminBSlugExpensesRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/integrations': {
      id: '/_authenticated/admin/b/$slug/integrations'
      path: '/integrations'
      fullPath: '/admin/b/$slug/integrations'
      preLoaderRoute: typeof AuthenticatedAdminBSlugIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/inventory': {
      id: '/_authenticated/admin/b/$slug/inventory'
      path: '/inventory'
      fullPath: '/admin/b/$slug/inventory'
      preLoaderRoute: typeof AuthenticatedAdminBSlugInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/pages': {
      id: '/_authenticated/admin/b/$slug/pages'
      path: '/pages'
      fullPath: '/admin/b/$slug/pages'
      preLoaderRoute: typeof AuthenticatedAdminBSlugPagesRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/reports': {
      id: '/_authenticated/admin/b/$slug/reports'
      path: '/reports'
      fullPath: '/admin/b/$slug/reports'
      preLoaderRoute: typeof AuthenticatedAdminBSlugReportsRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/settings': {
      id: '/_authenticated/admin/b/$slug/settings'
      path: '/settings'
      fullPath: '/admin/b/$slug/settings'
      preLoaderRoute: typeof AuthenticatedAdminBSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/team': {
      id: '/_authenticated/admin/b/$slug/team'
      path: '/team'
      fullPath: '/admin/b/$slug/team'
      preLoaderRoute: typeof AuthenticatedAdminBSlugTeamRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/customers/$customerId': {
      id: '/_authenticated/admin/b/$slug/customers/$customerId'
      path: '/$customerId'
      fullPath: '/admin/b/$slug/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedAdminBSlugCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugCustomersRoute
    }
    '/_authenticated/admin/b/$slug/orders/': {
      id: '/_authenticated/admin/b/$slug/orders/'
      path: '/orders'
      fullPath: '/admin/b/$slug/orders/'
      preLoaderRoute: typeof AuthenticatedAdminBSlugOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/orders/$id': {
      id: '/_authenticated/admin/b/$slug/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/b/$slug/orders/$id'
      preLoaderRoute: typeof AuthenticatedAdminBSlugOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugRouteRoute
    }
    '/_authenticated/admin/b/$slug/reports/': {
      id: '/_authenticated/admin/b/$slug/reports/'
      path: '/'
      fullPath: '/admin/b/$slug/reports/'
      preLoaderRoute: typeof AuthenticatedAdminBSlugReportsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugReportsRoute
    }
    '/_authenticated/admin/b/$slug/reports/customers': {
      id: '/_authenticated/admin/b/$slug/reports/customers'
      path: '/customers'
      fullPath: '/admin/b/$slug/reports/customers'
      preLoaderRoute: typeof AuthenticatedAdminBSlugReportsCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugReportsRoute
    }
    '/_authenticated/admin/b/$slug/reports/export': {
      id: '/_authenticated/admin/b/$slug/reports/export'
      path: '/export'
      fullPath: '/admin/b/$slug/reports/export'
      preLoaderRoute: typeof AuthenticatedAdminBSlugReportsExportRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugReportsRoute
    }
    '/_authenticated/admin/b/$slug/reports/products': {
      id: '/_authenticated/admin/b/$slug/reports/products'
      path: '/products'
      fullPath: '/admin/b/$slug/reports/products'
      preLoaderRoute: typeof AuthenticatedAdminBSlugReportsProductsRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugReportsRoute
    }
    '/_authenticated/admin/b/$slug/reports/sales': {
      id: '/_authenticated/admin/b/$slug/reports/sales'
      path: '/sales'
      fullPath: '/admin/b/$slug/reports/sales'
      preLoaderRoute: typeof AuthenticatedAdminBSlugReportsSalesRouteImport
      parentRoute: typeof AuthenticatedAdminBSlugReportsRoute
    }
  }
}

interface SlugRouteRouteChildren {
  SlugCategoryRoute: typeof SlugCategoryRoute
  SlugAccountRoute: typeof SlugAccountRoute
  SlugAuthRoute: typeof SlugAuthRoute
  SlugAuthConfirmedRoute: typeof SlugAuthConfirmedRoute
  SlugCheckoutRoute: typeof SlugCheckoutRoute
  SlugSearchRoute: typeof SlugSearchRoute
  SlugWishlistRoute: typeof SlugWishlistRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugPageIdxRoute: typeof SlugPageIdxRoute
  SlugProductSplatRoute: typeof SlugProductSplatRoute
  SlugProductIdRoute: typeof SlugProductIdRoute
  SlugThankYouOrderIdRoute: typeof SlugThankYouOrderIdRoute
}

const SlugRouteRouteChildren: SlugRouteRouteChildren = {
  SlugCategoryRoute: SlugCategoryRoute,
  SlugAccountRoute: SlugAccountRoute,
  SlugAuthRoute: SlugAuthRoute,
  SlugAuthConfirmedRoute: SlugAuthConfirmedRoute,
  SlugCheckoutRoute: SlugCheckoutRoute,
  SlugSearchRoute: SlugSearchRoute,
  SlugWishlistRoute: SlugWishlistRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugPageIdxRoute: SlugPageIdxRoute,
  SlugProductSplatRoute: SlugProductSplatRoute,
  SlugProductIdRoute: SlugProductIdRoute,
  SlugThankYouOrderIdRoute: SlugThankYouOrderIdRoute,
}

const SlugRouteRouteWithChildren = SlugRouteRoute._addFileChildren(
  SlugRouteRouteChildren,
)

interface AuthenticatedAdminBSlugCustomersRouteChildren {
  AuthenticatedAdminBSlugCustomersCustomerIdRoute: typeof AuthenticatedAdminBSlugCustomersCustomerIdRoute
}

const AuthenticatedAdminBSlugCustomersRouteChildren: AuthenticatedAdminBSlugCustomersRouteChildren =
  {
    AuthenticatedAdminBSlugCustomersCustomerIdRoute:
      AuthenticatedAdminBSlugCustomersCustomerIdRoute,
  }

const AuthenticatedAdminBSlugCustomersRouteWithChildren =
  AuthenticatedAdminBSlugCustomersRoute._addFileChildren(
    AuthenticatedAdminBSlugCustomersRouteChildren,
  )

interface AuthenticatedAdminBSlugReportsRouteChildren {
  AuthenticatedAdminBSlugReportsCustomersRoute: typeof AuthenticatedAdminBSlugReportsCustomersRoute
  AuthenticatedAdminBSlugReportsExportRoute: typeof AuthenticatedAdminBSlugReportsExportRoute
  AuthenticatedAdminBSlugReportsProductsRoute: typeof AuthenticatedAdminBSlugReportsProductsRoute
  AuthenticatedAdminBSlugReportsSalesRoute: typeof AuthenticatedAdminBSlugReportsSalesRoute
  AuthenticatedAdminBSlugReportsIndexRoute: typeof AuthenticatedAdminBSlugReportsIndexRoute
}

const AuthenticatedAdminBSlugReportsRouteChildren: AuthenticatedAdminBSlugReportsRouteChildren =
  {
    AuthenticatedAdminBSlugReportsCustomersRoute:
      AuthenticatedAdminBSlugReportsCustomersRoute,
    AuthenticatedAdminBSlugReportsExportRoute:
      AuthenticatedAdminBSlugReportsExportRoute,
    AuthenticatedAdminBSlugReportsProductsRoute:
      AuthenticatedAdminBSlugReportsProductsRoute,
    AuthenticatedAdminBSlugReportsSalesRoute:
      AuthenticatedAdminBSlugReportsSalesRoute,
    AuthenticatedAdminBSlugReportsIndexRoute:
      AuthenticatedAdminBSlugReportsIndexRoute,
  }

const AuthenticatedAdminBSlugReportsRouteWithChildren =
  AuthenticatedAdminBSlugReportsRoute._addFileChildren(
    AuthenticatedAdminBSlugReportsRouteChildren,
  )

interface AuthenticatedAdminBSlugRouteRouteChildren {
  AuthenticatedAdminBSlugCampaignsRoute: typeof AuthenticatedAdminBSlugCampaignsRoute
  AuthenticatedAdminBSlugCategoriesRoute: typeof AuthenticatedAdminBSlugCategoriesRoute
  AuthenticatedAdminBSlugCommunicationsRoute: typeof AuthenticatedAdminBSlugCommunicationsRoute
  AuthenticatedAdminBSlugCustomersRoute: typeof AuthenticatedAdminBSlugCustomersRouteWithChildren
  AuthenticatedAdminBSlugDashboardRoute: typeof AuthenticatedAdminBSlugDashboardRoute
  AuthenticatedAdminBSlugDiscountsRoute: typeof AuthenticatedAdminBSlugDiscountsRoute
  AuthenticatedAdminBSlugExpensesRoute: typeof AuthenticatedAdminBSlugExpensesRoute
  AuthenticatedAdminBSlugIntegrationsRoute: typeof AuthenticatedAdminBSlugIntegrationsRoute
  AuthenticatedAdminBSlugInventoryRoute: typeof AuthenticatedAdminBSlugInventoryRoute
  AuthenticatedAdminBSlugPagesRoute: typeof AuthenticatedAdminBSlugPagesRoute
  AuthenticatedAdminBSlugReportsRoute: typeof AuthenticatedAdminBSlugReportsRouteWithChildren
  AuthenticatedAdminBSlugSettingsRoute: typeof AuthenticatedAdminBSlugSettingsRoute
  AuthenticatedAdminBSlugTeamRoute: typeof AuthenticatedAdminBSlugTeamRoute
  AuthenticatedAdminBSlugOrdersIdRoute: typeof AuthenticatedAdminBSlugOrdersIdRoute
  AuthenticatedAdminBSlugOrdersIndexRoute: typeof AuthenticatedAdminBSlugOrdersIndexRoute
}

const AuthenticatedAdminBSlugRouteRouteChildren: AuthenticatedAdminBSlugRouteRouteChildren =
  {
    AuthenticatedAdminBSlugCampaignsRoute:
      AuthenticatedAdminBSlugCampaignsRoute,
    AuthenticatedAdminBSlugCategoriesRoute:
      AuthenticatedAdminBSlugCategoriesRoute,
    AuthenticatedAdminBSlugCommunicationsRoute:
      AuthenticatedAdminBSlugCommunicationsRoute,
    AuthenticatedAdminBSlugCustomersRoute:
      AuthenticatedAdminBSlugCustomersRouteWithChildren,
    AuthenticatedAdminBSlugDashboardRoute:
      AuthenticatedAdminBSlugDashboardRoute,
    AuthenticatedAdminBSlugDiscountsRoute:
      AuthenticatedAdminBSlugDiscountsRoute,
    AuthenticatedAdminBSlugExpensesRoute: AuthenticatedAdminBSlugExpensesRoute,
    AuthenticatedAdminBSlugIntegrationsRoute:
      AuthenticatedAdminBSlugIntegrationsRoute,
    AuthenticatedAdminBSlugInventoryRoute:
      AuthenticatedAdminBSlugInventoryRoute,
    AuthenticatedAdminBSlugPagesRoute: AuthenticatedAdminBSlugPagesRoute,
    AuthenticatedAdminBSlugReportsRoute:
      AuthenticatedAdminBSlugReportsRouteWithChildren,
    AuthenticatedAdminBSlugSettingsRoute: AuthenticatedAdminBSlugSettingsRoute,
    AuthenticatedAdminBSlugTeamRoute: AuthenticatedAdminBSlugTeamRoute,
    AuthenticatedAdminBSlugOrdersIdRoute: AuthenticatedAdminBSlugOrdersIdRoute,
    AuthenticatedAdminBSlugOrdersIndexRoute:
      AuthenticatedAdminBSlugOrdersIndexRoute,
  }

const AuthenticatedAdminBSlugRouteRouteWithChildren =
  AuthenticatedAdminBSlugRouteRoute._addFileChildren(
    AuthenticatedAdminBSlugRouteRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBrandsRoute: typeof AuthenticatedAdminBrandsRoute
  AuthenticatedAdminCampaignsRoute: typeof AuthenticatedAdminCampaignsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminExpensesRoute: typeof AuthenticatedAdminExpensesRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBSlugRouteRoute: typeof AuthenticatedAdminBSlugRouteRouteWithChildren
  AuthenticatedAdminSuperRequestsRoute: typeof AuthenticatedAdminSuperRequestsRoute
  AuthenticatedAdminSuperSettingsRoute: typeof AuthenticatedAdminSuperSettingsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBrandsRoute: AuthenticatedAdminBrandsRoute,
  AuthenticatedAdminCampaignsRoute: AuthenticatedAdminCampaignsRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminExpensesRoute: AuthenticatedAdminExpensesRoute,
  AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBSlugRouteRoute:
    AuthenticatedAdminBSlugRouteRouteWithChildren,
  AuthenticatedAdminSuperRequestsRoute: AuthenticatedAdminSuperRequestsRoute,
  AuthenticatedAdminSuperSettingsRoute: AuthenticatedAdminSuperSettingsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRouteRoute: SlugRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardRoute: OnboardRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  PlatformFilenameRoute: PlatformFilenameRoute,
  ApiCronCleanupBenefitReceiptsRoute: ApiCronCleanupBenefitReceiptsRoute,
  ApiOrdersStatusRoute: ApiOrdersStatusRoute,
  ApiPublicPaymentsCreateTapChargeRoute: ApiPublicPaymentsCreateTapChargeRoute,
  ApiPublicPaymentsTapRedirectRoute: ApiPublicPaymentsTapRedirectRoute,
  ApiPublicWebhooksTapRoute: ApiPublicWebhooksTapRoute,
  BrandsBrandIdKindFilenameRoute: BrandsBrandIdKindFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
