-- Shared private asset bucket used by logos, favicons, fonts, product media,
-- category images, receipt attachments and invoice assets.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'invoice-assets',
  'invoice-assets',
  false,
  52428800,
  ARRAY[
    'image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml',
    'image/x-icon', 'image/vnd.microsoft.icon',
    'video/mp4', 'video/webm', 'video/quicktime',
    'font/woff', 'font/woff2', 'font/ttf', 'font/otf', 'font/sfnt',
    'application/font-woff', 'application/x-font-ttf',
    'application/x-font-opentype', 'application/octet-stream', 'application/pdf'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "Users manage own invoice assets" ON storage.objects;
CREATE POLICY "Users manage own invoice assets"
ON storage.objects FOR ALL TO authenticated
USING (
  bucket_id = 'invoice-assets'
  AND auth.uid()::text = (storage.foldername(name))[1]
)
WITH CHECK (
  bucket_id = 'invoice-assets'
  AND auth.uid()::text = (storage.foldername(name))[1]
);

-- The bucket remains private. Assets are delivered through the long-lived
-- signed URLs generated by the application after a successful upload.
DROP POLICY IF EXISTS "Public read invoice assets" ON storage.objects;
DROP POLICY IF EXISTS "Owners read own invoice assets" ON storage.objects;
