// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export function getEnvVariable(name: string): string | undefined {
  const viteName = name.startsWith("VITE_") ? name : `VITE_${name}`;
  const unprefixed = name.startsWith("VITE_") ? name.slice(5) : name;

  // 1. Try real live runtime process.env or globalThis.__CLOUDFLARE_ENV__ (bypassing Vite's compile-time static rewriting)
  try {
    const g = globalThis as any;
    const liveEnv = g["__CLOUDFLARE_ENV__"] || g["process"]?.["env"];
    if (liveEnv) {
      if (liveEnv[name]) return liveEnv[name];
      if (liveEnv[viteName]) return liveEnv[viteName];
      if (liveEnv[unprefixed]) return liveEnv[unprefixed];
    }
  } catch {}

  // 2. Try import.meta.env (Vite build-time injection)
  try {
    const metaEnv = (import.meta as any).env;
    if (metaEnv?.[name]) return metaEnv[name];
    if (metaEnv?.[viteName]) return metaEnv[viteName];
    if (metaEnv?.[unprefixed]) return metaEnv[unprefixed];
  } catch {}

  // 3. Fallback to standard process.env (which Vite rewrites statically at build time)
  try {
    if (process.env?.[name]) return process.env[name];
    if (process.env?.[viteName]) return process.env[viteName];
    if (process.env?.[unprefixed]) return process.env[unprefixed];
  } catch {}

  // 4. Try globalThis fallbacks
  try {
    const g = globalThis as any;
    if (g?.[name]) return g[name];
    if (g?.[viteName]) return g[viteName];
    if (g?.[unprefixed]) return g[unprefixed];
  } catch {}

  return undefined;
}

export async function getEnvVariableAsync(name: string): Promise<string | undefined> {
  const viteName = name.startsWith("VITE_") ? name : `VITE_${name}`;
  const unprefixed = name.startsWith("VITE_") ? name.slice(5) : name;

  // 1. Try Cloudflare request context (runtime environment variables)
  if (typeof window === "undefined") {
    try {
      const vinxiHttp = "vinxi/http";
      const { getEvent } = await import(vinxiHttp);
      const event = getEvent();
      const env =
        event?.context?.cloudflare?.env ||
        (event?.context as any)?.env ||
        event?.context?.cloudflare ||
        (event?.context as any)?.cloudflare?.env;
      if (env) {
        if (env[name]) return env[name];
        if (env[viteName]) return env[viteName];
        if (env[unprefixed]) return env[unprefixed];
      }
    } catch (e) {
      if (name === "GEMINI_API_KEY") {
        console.error(`[Env Debug] Error reading Cloudflare context:`, e);
      }
    }
  }

  // 2. Fall back to standard synchronous checks
  return getEnvVariable(name);
}

export async function getEnvDiagnostics(): Promise<{
  keys: string[];
  hasProcess: boolean;
  hasCloudflare: boolean;
}> {
  const keys = new Set<string>();
  let hasProcess = false;
  let hasCloudflare = false;

  // 1. Live process.env (bracket notation to bypass Vite compilation)
  try {
    const g = globalThis as any;
    const liveEnv = g["process"]?.["env"];
    if (liveEnv) {
      hasProcess = true;
      Object.keys(liveEnv).forEach((k) => keys.add(k));
    }
  } catch {}

  // 2. Cloudflare request context
  if (typeof window === "undefined") {
    try {
      const vinxiHttp = "vinxi/http";
      const { getEvent } = await import(vinxiHttp);
      const event = getEvent();
      const env =
        event?.context?.cloudflare?.env ||
        (event?.context as any)?.env ||
        event?.context?.cloudflare ||
        (event?.context as any)?.cloudflare?.env;
      if (env) {
        hasCloudflare = true;
        Object.keys(env).forEach((k) => keys.add(k));
      }
    } catch {}
  }

  // 3. Static process.env (Vite compilation will rewrite)
  try {
    if (process.env) {
      Object.keys(process.env).forEach((k) => keys.add(k));
    }
  } catch {}

  // 4. import.meta.env
  try {
    const metaEnv = (import.meta as any).env;
    if (metaEnv) {
      Object.keys(metaEnv).forEach((k) => keys.add(k));
    }
  } catch {}

  // Filter out sensitive-looking keys for safety, but keep key schemas
  const filteredKeys = Array.from(keys).map((k) => {
    if (k.length > 30) return `${k.substring(0, 5)}... (len: ${k.length})`;
    return k;
  });

  return {
    keys: filteredKeys,
    hasProcess,
    hasCloudflare,
  };
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    let SUPABASE_URL =
      (await getEnvVariableAsync("SUPABASE_URL")) ||
      (await getEnvVariableAsync("VITE_SUPABASE_URL"));
    if (
      SUPABASE_URL &&
      !SUPABASE_URL.startsWith("http://") &&
      !SUPABASE_URL.startsWith("https://")
    ) {
      SUPABASE_URL = `https://${SUPABASE_URL}`;
    }
    const SUPABASE_PUBLISHABLE_KEY =
      (await getEnvVariableAsync("SUPABASE_PUBLISHABLE_KEY")) ||
      (await getEnvVariableAsync("VITE_SUPABASE_ANON_KEY")) ||
      (await getEnvVariableAsync("VITE_SUPABASE_PUBLISHABLE_KEY"));

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please add them to your hosting provider settings.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const { getRequest: getReq } = await import("@tanstack/react-start/server");
    const request = getReq();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    if (token.split(".").length !== 3) {
      throw new Error("Unauthorized: Invalid token");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    // Centered Impersonation Mutation Safeguard Block
    const cookieHeader = request.headers.get("cookie");
    let isImpersonating = false;
    if (cookieHeader) {
      const match = cookieHeader.match(/(^|;)\s*boutq_impersonation_token\s*=\s*([^;]+)/);
      if (match) {
        isImpersonating = true;
      }
    }

    if (isImpersonating && request.method !== "GET") {
      const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
      const { data: setting } = await supabaseAdmin
        .from("system_settings")
        .select("superadmin_impersonation_mutation_allowed")
        .eq("id", 1)
        .maybeSingle();

      if (setting?.superadmin_impersonation_mutation_allowed !== true) {
        throw new Error("Impersonation Mode is currently set to Read-Only by System Policy.");
      }
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);

/**
 * Retrieves Gemini credentials (API key and optional custom model) from
 * either the system environment variables or the database-backed integration settings.
 * This completely bypasses hosting-provider environmental issues.
 */
export async function getGeminiCredentials(
  supabase: any,
  userId: string,
): Promise<{
  apiKey: string | undefined;
  model: string | undefined;
  diagnostics?: string;
}> {
  let apiKey = await getEnvVariableAsync("GEMINI_API_KEY");
  let model: string | undefined = undefined;
  const traces: string[] = [];

  traces.push(`Env key state: ${apiKey ? "present" : "absent"}`);
  traces.push(`User ID: ${userId}`);

  // Resolve profile and brand_id
  let resolvedBrandId: string | null = null;
  let profile: any = null;

  // 1. Try fetching profile using the user-authenticated supabase client first!
  // This is 100% safe, respects RLS, and doesn't require any service role key.
  try {
    const { data: p, error: pErr } = await supabase
      .from("profiles")
      .select("brand_id, role, status")
      .eq("id", userId)
      .single();

    if (pErr) {
      traces.push(`[User Client Profile] fetch err: ${pErr.message}`);
    } else {
      profile = p;
      traces.push(
        `[User Client Profile] loaded: brand_id=${profile?.brand_id}, role=${profile?.role}, status=${profile?.status}`,
      );
    }
  } catch (uEx: any) {
    traces.push(`[User Client Profile] exception: ${uEx.message}`);
  }

  // 2. If user-authenticated profile query failed/empty, try admin client if available
  if (!profile) {
    try {
      const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
      const { data: p, error: pErr } = await supabaseAdmin
        .from("profiles")
        .select("brand_id, role, status")
        .eq("id", userId)
        .single();
      if (pErr) {
        traces.push(`[Admin Profile] fetch err: ${pErr.message}`);
      } else {
        profile = p;
        traces.push(
          `[Admin Profile] loaded: brand_id=${profile?.brand_id}, role=${profile?.role}, status=${profile?.status}`,
        );
      }
    } catch (adminEx: any) {
      traces.push(`[Admin Profile] exception: ${adminEx.message}`);
    }
  }

  // 3. Resolve active brand ID from either URL referer or profile fallback
  try {
    const { getRequest: getReq } = await import("@tanstack/react-start/server");
    const request = getReq();
    const referer = request?.headers?.get("referer");
    traces.push(`[Referer] ${referer || "none"}`);
    if (referer) {
      const url = new URL(referer);
      const match = url.pathname.match(/\/admin\/b\/([^/]+)/);
      if (match && match[1]) {
        const slug = match[1].toLowerCase().trim();
        traces.push(`[Referer] parsed slug: ${slug}`);

        // Try resolving brand ID using user-authenticated client first
        const { data: brand, error: brandErr } = await supabase
          .from("brands")
          .select("id")
          .eq("slug", slug)
          .single();

        if (!brandErr && brand?.id) {
          resolvedBrandId = brand.id;
          traces.push(`[Referer User Client] resolved brand_id: ${resolvedBrandId}`);
        } else {
          traces.push(`[Referer User Client] brand query err: ${brandErr?.message || "empty"}`);
          // Try admin fallback if user-authenticated query failed
          try {
            const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
            const { data: abrand, error: abrandErr } = await supabaseAdmin
              .from("brands")
              .select("id")
              .eq("slug", slug)
              .single();
            if (!abrandErr && abrand?.id) {
              resolvedBrandId = abrand.id;
              traces.push(`[Referer Admin] resolved brand_id: ${resolvedBrandId}`);
            }
          } catch {}
        }
      }
    }
  } catch (refererEx: any) {
    traces.push(`[Referer] resolution exception: ${refererEx.message}`);
  }

  if (!resolvedBrandId && profile?.brand_id) {
    resolvedBrandId = profile.brand_id;
    traces.push(`[Fallback] using profile brand_id: ${resolvedBrandId}`);
  }

  if (resolvedBrandId) {
    // Secrets are decrypted only for the server-side service role. They are
    // never exposed through an authenticated browser RPC or a direct table read.
    try {
      const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
      const { data, error: adminIntErr } = await (supabaseAdmin.rpc as any)(
        "get_integration_credential_secret",
        { p_brand_id: resolvedBrandId, p_provider: "gemini" },
      );
      const integration = data?.[0];
      if (!adminIntErr && integration?.api_key) {
        apiKey = integration.api_key;
        model = integration.base_url?.trim() || undefined;
        traces.push(`[Vault] Gemini credential loaded server-side`);
      } else if (adminIntErr) {
        traces.push(`[Vault] credential lookup error: ${adminIntErr.message}`);
      }
    } catch (adminEx: any) {
      traces.push(`[Vault] credential lookup exception: ${adminEx.message}`);
    }
  } else {
    traces.push(`[Error] Could not resolve brand_id from profile or referer`);
  }

  return { apiKey, model, diagnostics: traces.join(" | ") };
}
