// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getEnvVariable } from "@/lib/runtime-env";

const FALLBACK_SUPABASE_URL = "https://ikciahnuqhemvnyfvbyp.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_mZLaZzhuKAqvgwpsZmRslQ_YahrHqxy";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export function resolveSupabaseUrl(): string {
  let url =
    getEnvVariable("VITE_SUPABASE_URL") ||
    getEnvVariable("SUPABASE_URL") ||
    getEnvVariable("NEXT_PUBLIC_SUPABASE_URL") ||
    (typeof import.meta !== "undefined" && (import.meta as any).env?.VITE_SUPABASE_URL) ||
    (typeof import.meta !== "undefined" && (import.meta as any).env?.NEXT_PUBLIC_SUPABASE_URL) ||
    (typeof process !== "undefined" && process.env?.VITE_SUPABASE_URL) ||
    (typeof process !== "undefined" && process.env?.SUPABASE_URL) ||
    FALLBACK_SUPABASE_URL;

  if (url && !url.startsWith("http://") && !url.startsWith("https://")) {
    url = `https://${url}`;
  }

  return url;
}

export function resolveSupabasePublishableKey(): string {
  return (
    getEnvVariable("VITE_SUPABASE_PUBLISHABLE_KEY") ||
    getEnvVariable("VITE_SUPABASE_ANON_KEY") ||
    getEnvVariable("SUPABASE_PUBLISHABLE_KEY") ||
    getEnvVariable("SUPABASE_ANON_KEY") ||
    getEnvVariable("NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY") ||
    getEnvVariable("NEXT_PUBLIC_SUPABASE_ANON_KEY") ||
    (typeof import.meta !== "undefined" && (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY) ||
    (typeof import.meta !== "undefined" && (import.meta as any).env?.VITE_SUPABASE_ANON_KEY) ||
    (typeof import.meta !== "undefined" && (import.meta as any).env?.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY) ||
    (typeof process !== "undefined" && process.env?.VITE_SUPABASE_PUBLISHABLE_KEY) ||
    (typeof process !== "undefined" && process.env?.VITE_SUPABASE_ANON_KEY) ||
    (typeof process !== "undefined" && process.env?.SUPABASE_PUBLISHABLE_KEY) ||
    (typeof process !== "undefined" && process.env?.SUPABASE_ANON_KEY) ||
    FALLBACK_SUPABASE_PUBLISHABLE_KEY
  );
}

function createSupabaseClient() {
  const SUPABASE_URL = resolveSupabaseUrl();
  const SUPABASE_PUBLISHABLE_KEY = resolveSupabasePublishableKey();

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      experimental: { passkey: true },
    },
    realtime: {
      params: {
        apikey: SUPABASE_PUBLISHABLE_KEY,
      },
    },
  });
}

function createPublicSupabaseClient() {
  const url = resolveSupabaseUrl();
  const key = resolveSupabasePublishableKey();

  return createClient<Database>(url, key, {
    global: { fetch: createSupabaseFetch(key) },
    auth: {
      storageKey: "boutq-public-anonymous-auth",
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

let _publicSupabase: ReturnType<typeof createPublicSupabaseClient> | undefined;

export const publicSupabase = new Proxy({} as ReturnType<typeof createPublicSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_publicSupabase) _publicSupabase = createPublicSupabaseClient();
    return Reflect.get(_publicSupabase, prop, receiver);
  },
});
